### ISSUE TITLE
SSO setup. Django Team. 

### ISSUE THREAD

**Issue by BrianDavidAllen** [leavescalculator/LeavesCalculator#40]
## Description
This will allow a user to sign on with their PDX email.

## Acceptance Criteria
- [x] Lets the user sign in using their (fake) PDX email. 
- [x] Be able to long to console fake user's information 
- [x] Client-side token storage

**Comment by austinsheep** [comment]
Pull request #46 has added Django's auth login and logout system.  Next step is to use token authentication

**Comment by austinsheep** [comment]
https://github.com/leavescalculator/LeavesCalculator/commit/addc8091a1331b755006264efb7d32cb0d9329eb adds token auth.

Still need to add login screen and use async requests for the api
