### ISSUE TITLE
Write queries to get employee information from our dummy database 

### ISSUE THREAD

**Issue by BrianDavidAllen** [leavescalculator/LeavesCalculator#45]
## Description 
Write a master query(ies) that can get the needed information about a specific employee

##Acceptance criteria 
- [x] Output employee as CSV, JSON, plain text, or w/e 
- [x] Python dot operators from SQL queries
- [x] Store employee results in a temp Employee model for REST API to get info from

**Comment by angelicphan** [comment]
Don't need to 'drop' the Employee table. It will exists as a temporary data structure during life of the execution. Does not save anything to the database which is good.
