### ISSUE TITLE
Vue Login Page 

### ISSUE THREAD

**Issue by BrianDavidAllen** [leavescalculator/LeavesCalculator#55]
## Description 
Finish up the login page

## Acceptance Criteria 
- [x] Figure out how to store the token on client-side
- [x] Figure out expiration rules (two days, months,?) 
- [x] Set up expiration for server-side token

**Comment by austinsheep** [comment]
- We need to ask as to whether the admin will be a staff member's user account or a separate admin account.
- On a successful login, we could display the employee's information on the login page.
- We can also make the login page the place where previous reports are listed.
