### ISSUE TITLE
JSON Graph

### ISSUE THREAD

**Issue by BrianDavidAllen** [leavescalculator/LeavesCalculator#96]
## Requirements 
- [x] change add_hours -> add_time
- [x] add week field to add_time
- [x] Move questions name into title inside node
- [x] Rename nodes to unique string

**Comment by austinsheep** [comment]
Looks like display nodes are falling into the try-catch in the parser for the admin dashboard.  Maybe we should consider adding a description field to nodes so we're not adding an option with the description as the title that has next_node as an invalid node id.

**Comment by BrianDavidAllen** [comment]
I'll look into it. Thanks for the feedback.
